"""Chart drawings — client-owned rows, one per instrument.

    `id` is generated by the client (TradingView's own drawing id), not by us —
    the only table where that's true. That's what makes the upsert batch work:
    the client already knows which id is which, so `ON CONFLICT (id)` overwrites
    the right row instead of us guessing.

    Deletes are tombstones (`deleted_at`), never physical rows: a drawing
    deleted on one device must still disappear on another that synced before
    the delete happened.

    The client only ever speaks in symbols (it never sees `instrument_id`), so
    every entry point resolves symbol -> instrument_id via `get_instrument_id`
    and every read joins back to `instruments.symbol` for the response.
"""

from app.core.db.database import query
from app.services.instruments import get_instrument_id


def get_drawings(user_id: str, symbol: str | None = None) -> list[dict]:
    """Returns the caller's own drawings, live and deleted, symbol optional.

        Args:
            user_id (str): The authenticated caller.
            symbol (str | None): Restrict to one instrument, uppercased.

        Returns:
            list[dict]: id, symbol, payload, updated_at, deleted_at.
    """
    sql = """
        SELECT ud.id, i.symbol, ud.payload, ud.updated_at, ud.deleted_at
        FROM user_drawings AS ud
        JOIN instruments AS i ON i.id = ud.instrument_id
        WHERE ud.user_id = %s
        """
    params = [user_id]

    if symbol:
        sql += " AND i.symbol = %s"
        params.append(symbol.upper())

    rows = query(sql, (*params,))
    return rows


def upsert_drawings(user_id: str, drawings: list[dict]) -> int:
    """Inserts or overwrites a batch of drawings, always owned by the caller.

        `user_id` always comes from the token, never from the body — a client
        cannot upsert a drawing into someone else's account by sending a
        different id.

        Args:
            user_id (str): The authenticated caller.
            drawings (list[dict]): Each with id, symbol, payload.

        Returns:
            int: How many rows were written.
    """
    sql = """
            INSERT INTO user_drawings (id, user_id, instrument_id, payload, deleted_at, updated_at)
            VALUES (%s, %s, %s, %s, NULL, now())
            ON CONFLICT (id) DO UPDATE
                SET instrument_id = EXCLUDED.instrument_id,
                    payload = EXCLUDED.payload,
                    deleted_at = NULL,
                    updated_at = now()
        """
    nbr_success_update = 0
    for d in drawings:
        instrument_id = get_instrument_id(d["symbol"])
        query(sql, (d["id"], user_id, instrument_id, d["payload"]), nothing_return=True)
        nbr_success_update += 1

    return nbr_success_update


def delete_drawings(user_id: str, ids: list[str]) -> None:
    """Tombstones the caller's own drawings — never a physical delete.

        Args:
            user_id (str): The authenticated caller.
            ids (list[str]): Drawing ids to tombstone.
    """
    sql = """
            UPDATE user_drawings
            SET deleted_at = now(), updated_at = now()
            WHERE user_id = %s AND id = ANY(%s)
        """
    params = (user_id, ids)

    query(sql, (*params,), nothing_return=True)
